[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ucbl_logger"]

[project]
name = "ucbl-logger"
version = "1.0.37"
description = "A User-Centric Behaviour Log Markup Language Logger"
readme = "README.md"
requires-python = ">=3.11"
license = "CC-BY-NC-ND-4.0"
authors = [
    {name = "Evan Erwee", email = "evan@erwee.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Topic :: Software Development :: Libraries",
]

dependencies = [
    "pytz",
    "kubernetes>=28.1.0",
    "psutil>=5.8.0",
    "boto3>=1.26.0",
]

[project.optional-dependencies]
test = [
    "pytest>=6.0",
    "pytest-cov>=2.0",
    "pytest-mock>=3.0",
    "moto[eks,ec2]>=4.0.0",
]
eks = [
    "opentelemetry-api>=1.0.0",
    "prometheus-client>=0.14.0",
]