apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-plane-core
  namespace: data-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-plane-core
  template:
    metadata:
      labels:
        app: data-plane-core
    spec:
      containers:
      - name: data-plane-core
        image: your-registry/data-plane-core:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SERVICE_NAME
          value: "data-plane-core"
        - name: NAMESPACE
          value: "data-plane"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"