apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphrag-toolkit
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphrag-toolkit
  template:
    metadata:
      labels:
        app: graphrag-toolkit
    spec:
      containers:
      - name: graphrag-toolkit
        image: your-registry/graphrag-toolkit:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: "graphrag-toolkit"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: graphrag-toolkit-service
  namespace: default
spec:
  selector:
    app: graphrag-toolkit
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP